/**
 * Live Analysis — Shared Types & Constants
 * 
 * Types used across the Smart Router, Tavily investigator, GPT judge, and Mistral auditor.
 * 
 * v2.0 — Sprint 1: Replaced Perplexity FactCheckContext with Tavily-based source model.
 */

// ─── Content Intent ──────────────────────────────────────────────────────────
// Determined by the Primary Judge based on the article's actual intention
export type ContentIntent = 'REPORT' | 'INVESTIGATION' | 'OPINION' | 'PROMO' | 'ACADEMIC';

// Pillar weights per Content Intent
export const INTENT_WEIGHTS: Record<ContentIntent, { transparency: number; editorial: number; semantic: number; logic: number }> = {
    REPORT: { transparency: 0.20, editorial: 0.30, semantic: 0.25, logic: 0.25 },
    INVESTIGATION: { transparency: 0.20, editorial: 0.40, semantic: 0.15, logic: 0.25 },
    OPINION: { transparency: 0.20, editorial: 0.20, semantic: 0.40, logic: 0.20 },
    PROMO: { transparency: 0.45, editorial: 0.25, semantic: 0.25, logic: 0.05 },
    ACADEMIC: { transparency: 0.20, editorial: 0.50, semantic: 0.15, logic: 0.15 },
};

export const VALID_INTENTS: ContentIntent[] = ['REPORT', 'INVESTIGATION', 'OPINION', 'PROMO', 'ACADEMIC'];

// ─── DISARM Codes ────────────────────────────────────────────────────────────
// Key manipulation techniques from the DISARM framework used in bias detection
export const DISARM_TECHNIQUES = {
    T0081: 'Cadrage émotionnel (Emotional Framing)',
    T0042: 'Homme de paille (Straw Man)',
    T0039: 'Cherry-picking (Sélection biaisée de données)',
    T0048: 'Appel à la peur (Fear-mongering)',
    T0049: 'Appel à l\'autorité (sans expertise)',
    T0046: 'Faux dilemme (False Dichotomy)',
    T0044: 'Généralisation abusive (Hasty Generalization)',
    T0087: 'Amplification de statistiques hors contexte',
    T0085: 'Titre trompeur (Misleading Headline)',
    T0082: 'Victimisation stratégique',
} as const;

export type DisarmCode = keyof typeof DISARM_TECHNIQUES;

// ─── Source Model (Tavily) ────────────────────────────────────────────────────
// Individual source returned by Tavily search
export interface FactCheckSource {
    url: string;
    title: string;
    content: string;         // Markdown pur (rawContent de Tavily, truncated)
    publishedDate?: string;
    domain: string;
    score: number;           // Tavily relevance score (0-1)
}

// Smart Router decision (multilingual queries for parallel Tavily searches)
export interface RoutingDecision {
    route: 'HOT_NEWS' | 'COLD_INVESTIGATION' | 'MIXED';
    query_fr: string;           // Requête optimisée en français
    query_en: string;           // Requête traduite en anglais
    query_local: string | null; // Requête dans la langue locale de l'événement (null si non pertinent)
}

// Consolidated context for the judges (replaces old Perplexity-specific FactCheckContext)
export interface FactCheckContext {
    sources: FactCheckSource[];    // Max 10 sources
    routingDecision: RoutingDecision;
}

// ─── Pillar Score ─────────────────────────────────────────────────────────────
// Individual pillar score with evidence and DISARM codes
export interface PillarScore {
    score: number;           // 0-100
    quote: string;           // Extract from article or source
    reasoning: string;       // Justification
    disarmCodes?: DisarmCode[]; // DISARM technique codes detected (Primary Judge)
}

// ─── Generated Article Content ────────────────────────────────────────────────
// Content generated by the Primary Judge alongside DISARM analysis
export interface GeneratedContent {
    title: string;              // Titre percutant
    summary: string;            // Résumé en 2 phrases
    content: string;            // Corps de l'article en Markdown
    tags: string[];             // Tags catégoriques
    imagePrompt: string | null; // Prompt DALL-E en anglais pour la couverture
    wikipedia_search_query: string | null; // Entity name for fetching Wikipedia image
}

// ─── Judge Verdict ────────────────────────────────────────────────────────────
// Full judge verdict
export interface JudgeVerdict {
    contentIntent: ContentIntent;
    pillarScores: {
        transparency: PillarScore;
        editorial: PillarScore;
        semantic: PillarScore;
        logic: PillarScore;
    };
    globalScore: number; // Weighted average based on Intent
    generatedContent?: GeneratedContent; // Only present on Primary Judge verdict
}

// ─── Pipeline Result ──────────────────────────────────────────────────────────
// Final result from the full pipeline
export interface LiveAnalysisResult {
    contentIntent: ContentIntent;
    pillarScores: {
        transparency: PillarScore;
        editorial: PillarScore;
        semantic: PillarScore;
        logic: PillarScore;
    };
    globalScore: number; // Final ScoreLiveBrut
    judges: {
        primary: JudgeVerdict;
        auditor: JudgeVerdict;
    };
    generatedContent?: GeneratedContent; // Article text generated by the Primary Judge
    sources?: FactCheckSource[]; // Array of Tavily sources used during analysis
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Calculate weighted global score from pillar scores and Content Intent.
 */
export function calculateWeightedScore(
    pillarScores: { transparency: PillarScore; editorial: PillarScore; semantic: PillarScore; logic: PillarScore },
    intent: ContentIntent
): number {
    const weights = INTENT_WEIGHTS[intent];
    const raw = (
        pillarScores.transparency.score * weights.transparency +
        pillarScores.editorial.score * weights.editorial +
        pillarScores.semantic.score * weights.semantic +
        pillarScores.logic.score * weights.logic
    );
    return Math.min(100, Math.max(0, Math.round(raw)));
}

/**
 * Format sources into a compact text block for LLM context injection.
 * Each source is numbered and includes title, domain, date, and content extract.
 */
export function formatSourcesForPrompt(sources: FactCheckSource[], maxCharsPerSource = 1500): string {
    if (sources.length === 0) return '[Aucune source trouvée]';

    return sources.map((s, i) => {
        const content = s.content.length > maxCharsPerSource
            ? s.content.slice(0, maxCharsPerSource) + '\n[... tronqué ...]'
            : s.content;
        const date = s.publishedDate ? ` | ${s.publishedDate}` : '';
        return `[Source ${i + 1}] ${s.title} (${s.domain}${date})\nURL: ${s.url}\n${content}`;
    }).join('\n\n---\n\n');
}
