import { prisma } from './db.js';

export async function buildUserDataExport(userId: string, currentSessionId?: string) {
  const user = await prisma.user.findUnique({
    where: { id: userId },
    select: {
      id: true,
      email: true,
      emailVerified: true,
      name: true,
      username: true,
      phone: true,
      avatarUrl: true,
      bannerUrl: true,
      role: true,
      subscriptionTier: true,
      dailyQueryCount: true,
      creditsArticle: true,
      organizationId: true,
      organizationRole: true,
      bio: true,
      isPublic: true,
      followersCount: true,
      followingCount: true,
      inviteCodeId: true,
      createdAt: true,
      updatedAt: true,
      usage: {
        select: {
          dailyCredits: true,
          lastResetAt: true,
          articlesCreated: true,
          articleQuotaResetAt: true,
          plan: true,
        },
      },
      betterAuthSessions: {
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          expiresAt: true,
          createdAt: true,
          updatedAt: true,
          ipAddress: true,
          userAgent: true,
        },
      },
      betterAuthAccounts: {
        orderBy: { createdAt: 'asc' },
        select: {
          id: true,
          accountId: true,
          providerId: true,
          scope: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      articles: {
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          slug: true,
          title: true,
          summary: true,
          content: true,
          structuredContent: true,
          status: true,
          imageUrl: true,
          categoryId: true,
          generationPrompt: true,
          generationConfig: true,
          generatedAt: true,
          generationVersion: true,
          aiLockedFields: true,
          aiSummary: true,
          factCheckScore: true,
          factCheckData: true,
          factCheckStatus: true,
          factCheckStartedAt: true,
          factCheckCompletedAt: true,
          factCheckError: true,
          isIndexed: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      saved: {
        orderBy: { savedAt: 'desc' },
        select: {
          articleId: true,
          savedAt: true,
          article: {
            select: {
              id: true,
              slug: true,
              title: true,
              summary: true,
              status: true,
              imageUrl: true,
              authorId: true,
              categoryId: true,
              createdAt: true,
              updatedAt: true,
            },
          },
        },
      },
      ArticleView: {
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          articleId: true,
          createdAt: true,
        },
      },
      reposts: {
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          articleId: true,
          createdAt: true,
        },
      },
      followers: {
        orderBy: { createdAt: 'desc' },
        select: {
          followerId: true,
          createdAt: true,
        },
      },
      following: {
        orderBy: { createdAt: 'desc' },
        select: {
          followingId: true,
          createdAt: true,
        },
      },
      ChatFolder: {
        orderBy: { createdAt: 'asc' },
        select: {
          id: true,
          name: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      sessions: {
        orderBy: { updatedAt: 'desc' },
        select: {
          id: true,
          topic: true,
          mode: true,
          folderId: true,
          createdAt: true,
          updatedAt: true,
          messages: {
            orderBy: { createdAt: 'asc' },
            select: {
              id: true,
              userId: true,
              role: true,
              content: true,
              sources: true,
              metadata: true,
              createdAt: true,
            },
          },
        },
      },
      messages: {
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          sessionId: true,
          role: true,
          content: true,
          sources: true,
          metadata: true,
          createdAt: true,
        },
      },
      comments: {
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          articleId: true,
          content: true,
          parentId: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      reactions: {
        orderBy: { createdAt: 'desc' },
        select: {
          articleId: true,
          type: true,
          createdAt: true,
        },
      },
      opinionPositions: {
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          articleId: true,
          selectedPosition: true,
          lacksContext: true,
          confirmedAt: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      contributions: {
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          articleId: true,
          targetContributionId: true,
          type: true,
          status: true,
          text: true,
          sourceUrl: true,
          bridgingScore: true,
          deletedAt: true,
          editedAt: true,
          editCount: true,
          createdAt: true,
          updatedAt: true,
        },
      },
      contributionValidations: {
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          contributionId: true,
          type: true,
          createdAt: true,
        },
      },
      contributionReports: {
        orderBy: { createdAt: 'desc' },
        select: {
          id: true,
          contributionId: true,
          reason: true,
          details: true,
          status: true,
          createdAt: true,
          updatedAt: true,
          reviewedAt: true,
        },
      },
    },
  });

  if (!user) return null;

  return {
    exportedAt: new Date().toISOString(),
    formatVersion: 1,
    account: {
      id: user.id,
      email: user.email,
      emailVerified: user.emailVerified,
      name: user.name,
      username: user.username,
      phone: user.phone,
      avatarUrl: user.avatarUrl,
      bannerUrl: user.bannerUrl,
      role: user.role,
      subscriptionTier: user.subscriptionTier,
      dailyQueryCount: user.dailyQueryCount,
      creditsArticle: user.creditsArticle,
      organizationId: user.organizationId,
      organizationRole: user.organizationRole,
      bio: user.bio,
      isPublic: user.isPublic,
      followersCount: user.followersCount,
      followingCount: user.followingCount,
      inviteCodeId: user.inviteCodeId,
      createdAt: user.createdAt,
      updatedAt: user.updatedAt,
    },
    usage: user.usage,
    auth: {
      sessions: user.betterAuthSessions.map((session) => ({
        id: session.id,
        expiresAt: session.expiresAt,
        createdAt: session.createdAt,
        updatedAt: session.updatedAt,
        ipAddress: session.ipAddress,
        userAgent: session.userAgent,
        current: session.id === currentSessionId,
      })),
      accounts: user.betterAuthAccounts,
    },
    content: {
      authoredArticles: user.articles,
      savedArticles: user.saved,
      articleViews: user.ArticleView,
      reposts: user.reposts,
    },
    social: {
      followers: user.followers,
      following: user.following,
    },
    chat: {
      folders: user.ChatFolder,
      sessions: user.sessions,
      userMessages: user.messages,
    },
    interactions: {
      comments: user.comments,
      reactions: user.reactions,
      opinionPositions: user.opinionPositions,
      contributions: user.contributions,
      contributionValidations: user.contributionValidations,
      contributionReports: user.contributionReports,
    },
  };
}
